config/routes.rb
Rails.application.routes.draw do
  root 'memberships#index'

  resources :clients
  resources :memberships
  resources :services
  
  devise_for :users, controllers: {
	sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Servicio creado con éxito.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Servicio actualizado con éxito.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Servicio eliminado con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:nombre, :precio)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(service) do |f| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="medium-6 columns">
      <%= f.label :Nombre %>
      <%= f.text_field :nombre %>
    </div>

    <div class="medium-6 columns">
      <%= f.label :Precio %>
      <%= f.text_field :precio %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Registrar servicio", class: 'button' %>
  </div>
<% end %>

app/views/services/edit.html.erb
<% if current_user.rol == 'Administrador' %>
	<h1>Editar Servicio</h1>

	<%= render 'form', service: @service %>

	<%= link_to 'Mostrar', @service, class: 'button' %> |
	<%= link_to 'Volver', services_path, class: 'button success' %>
<% else %>
	<h3>Usted no tiene permisos necesarios para acceder aqui</h3>
<% end %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.rol == 'Administrador' %>
  <h1>Administrar Servicios</h1>

  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Precio</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%= service.nombre %></td>
          <td id='p'>
            <script type="text/javascript">
              document.getElementById('p').innerHTML=accounting.formatMoney(<%= service.precio %>, "$", 2, ",", ".");
            </script>
          </td>
          <td><%= link_to 'Mostrar', service, class: 'button success' %></td>
          <td><%= link_to 'Editar', edit_service_path(service), class: 'button'%></td>
          <td><%= link_to 'Eliminar', service, method: :delete, data: { confirm: '¿Está seguro?' }, class: 'button alert' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nuevo servicio', new_service_path, class: 'button' %>
<% else %>
	<h3>Usted no tiene permisos necesarios para acceder aqui</h3>
<% end %>

app/views/services/new.html.erb
<% if current_user.rol == 'Administrador' %>
	<h1 class="text-center">Nuevo Servicio</h1>

	<%= render 'form', service: @service %>

	<%= link_to 'Volver', services_path, class: 'button success' %>
<% else %>
	<h3>Usted no tiene permisos necesarios para acceder aqui</h3>
<% end %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.rol == 'Administrador' %>
	<p>
  		<strong>Nombre:</strong>
  		<%= @service.nombre %>
	</p>

	<p>
		<strong>Precio:</strong>
  		<%= @service.precio %>
	</p>

	<%= link_to 'Editar', edit_service_path(@service), class: 'button' %> |
	<%= link_to 'Volver', services_path, class: 'button success' %>
<% else %>
	<h3>Usted no tiene permisos necesarios para acceder aqui</h3>
<% end %>