config/routes.rb
Rails.application.routes.draw do
  root 'memberships#index'

  resources :clients
  resources :memberships
  resources :services
  
  devise_for :users, controllers: {
	sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/membership.rb
class Membership < ApplicationRecord
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    if current_user.rol == 'Administrador'
      @memberships = Membership.all
    else
      @memberships = Membership.where(id_cliente: Client.where(id_usuario: current_user.id)[0].id)
    end
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membrecía creada con éxito.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membrecía actualizada con éxito.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membrecía eliminada con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:id_cliente, :id_servicio, :fecha_inicio, :fecha_fin)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(membership) do |f| %>
	<% if membership.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

			<ul>
			<% membership.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
  	<div class="row">
    	<div class="medium-6 columns">
			<%= f.label :Cliente %>
			<%= f.collection_select :id_cliente, Client.order(:nombre), :id, :apellidos, include_blank: false %>
		</div>

		<div class="medium-6 columns">
			<%= f.label :Servicio %>
			<%= f.collection_select :id_servicio, Service.order(:nombre), :id, :nombre, include_blank: false %>
		</div>
	</div>

  <div class="row">
    <div class="medium-6 columns">
		<%= f.label :Fecha_contrato %>
		<%= f.date_select :fecha_inicio %>
	</div>

	<div class="medium-6 columns">
		<%= f.label :Fecha_vencimiento %>
		<%= f.date_select :fecha_fin %>
	</div>
  </div>
	<div class="actions">
		<%= f.submit "Registrar", class: 'button' %>
	</div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editar membrecía</h1>

<% if current_user.rol == 'Administrador' %>
	<%= render 'form', membership: @membership %>

	<%= link_to 'Mostrar', @membership, class: 'button' %> |
	<%= link_to 'Volver', memberships_path, class: 'button success' %>
<% else %>
	<h3>Usted no tiene permisos necesarios para acceder aqui</h3>
<% end %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= current_user.rol == 'Administrador' ? 'Administrar ':'Mis '%>Membrecías</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Servicio</th>
      <th>Fecha inicio</th>
      <th>Fecha fin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <% @aux = Client.where(id: membership.id_cliente)[0] %>
        <td><%= @aux.nombre + ' ' + @aux.apellidos %></td>
        <td><%= Service.where(id: membership.id_servicio)[0].nombre %></td>
        <td><%= membership.fecha_inicio %></td>
        <td><%= membership.fecha_fin %></td>
        <% if current_user.rol == 'Administrador' %>
          <td><%= link_to 'Mostrar', membership, class: 'button success' %></td>
          <td><%= link_to 'Editar', edit_membership_path(membership), class: 'button' %></td>
          <td><%= link_to 'Eliminar', membership, method: :delete, data: { confirm: '¿Está seguro?' }, class: 'button alert round' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.rol == 'Administrador' %>
  <%= link_to '+', new_membership_path, class: 'button' %>
<% end %>

app/views/memberships/new.html.erb
<h1 class="text-center">Nueva membrecía</h1>

<% if current_user.rol == 'Administrador' %>
	<%= render 'form', membership: @membership %>

	<%= link_to 'Volver', memberships_path, class: 'button success' %>
<% else %>
	<h3>Usted no tiene permisos necesarios para acceder aqui</h3>
<% end %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.rol == 'Administrador' %>
	<p>
  		<strong>Cliente:</strong>
  		<% @aux = Client.where(id: @membership.id_cliente)[0] %>
  		<%= @aux.nombre + ' ' + @aux.apellidos %>
	</p>

	<p>
  		<strong>Servicio:</strong>
  		<%= Service.where(id: @membership.id_servicio)[0].nombre %>
	</p>

	<p>
  		<strong>Fecha inicio:</strong>
  		<%= @membership.fecha_inicio %>
	</p>

	<p>
  		<strong>Fecha fin:</strong>
  		<%= @membership.fecha_fin %>
	</p>

	<%= link_to 'Editar', edit_membership_path(@membership), class: 'button' %> |
	<%= link_to 'Volver', memberships_path, class: 'button success' %>
<% else %>
	<h3>Usted no tiene permisos necesarios para acceder aqui</h3>
<% end %>