config/routes.rb
Rails.application.routes.draw do
  root 'memberships#index'

  resources :clients
  resources :memberships
  resources :services
  
  devise_for :users, controllers: {
	sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Aplicacion Final Ruby On Rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <ul>
      <li>
        <%= image_tag 'icono.png', :width=> 50, :height =>50, class: 'icono'%>
      </li>
      <% if user_signed_in? %>
        <% if current_user.rol == 'Administrador' %>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">Membrecias</a>
            <div class="dropdown-content">
              <%= link_to 'Lista de membrecias', memberships_path %>
              <%= link_to 'Nueva membrecia', new_membership_path %>
            </div>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">Servicios</a>
            <div class="dropdown-content">
              <%= link_to 'Lista de servicios', services_path %>
              <%= link_to 'Nueva servicios', new_service_path %>
            </div>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">Clientes</a>
            <div class="dropdown-content">
              <%= link_to 'Lista de clientes', clients_path %>
              <%= link_to 'Nueva clientes', new_client_path %>
            </div>
          </li>
        <% else %>
          <li><%= link_to 'Mis membrecias', memberships_path %></li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">Información</a>
            <div class="dropdown-content">
              <% @aux = Client.where(id_usuario: current_user.id)[0] %>
              <%= link_to 'Ver mi información', @aux %>
              <%= link_to 'Editar mi información', edit_client_path(@aux) %>
            </div>
          </li>
        <% end %>
        <li class="lir1"><%= link_to 'Cerrar sesión', destroy_user_session_path, :method => :delete %></li>
        <li class="lir2"><%= link_to 'Editar perfil', edit_user_registration_path %></li>
        <li class="lir2"><a><%= current_user.email %></a></li>
      <% else %>
        <li class="lir1"><%= link_to 'Registro', new_user_registration_path %></li>
        <li class="lir2"><%= link_to 'Iniciar sesión', new_user_session_path %></li>
      <% end %>
    </ul>

    <%= yield %>

  </body>
</html>